language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

# command to install dependencies
before_install:
  - pip install poetry

install:
  - poetry install
# command to run tests
script:
  - flake8 ./app.py